### ISSUE TITLE
Update documentation for `-rotation-alignment` properties?

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapbox-gl-style-spec#448] opened 2016-05-03 20:10 UTC
I think the default [here](https://github.com/mapbox/mapbox-gl-style-spec/blob/874eb64699a48cc32bb55f3032aa376113504219/reference/v8.json#L476) does not seem to match up with the [rendering implementation](https://github.com/mapbox/mapbox-gl-js/blob/31dc4ac9cf40f561a0567df38909a323a3bd9c05/js/style/style_layer/symbol_style_layer.js#L29-L32).

**Comment by jfirebaugh** [comment] 2016-05-03 22:03
Duplicate of #235.

**Closed as completed by jfirebaugh** 2016-05-03 22:03 UTC
