### ISSUE TITLE
Add "required" to layer source and ref sections

### ISSUE THREAD

**Issue by danswick** [mapbox/mapbox-gl-style-spec#509] opened 2016-09-27 23:06 UTC
Because `background` layers don't require one, a `source` property is technically optional. However, a layer without a `source` or `ref` fails validation, which seems a bit incongruous. 

![image](https://cloud.githubusercontent.com/assets/2365503/18895205/b105ae2a-84cc-11e6-8301-3c9463bbf72a.png)

**Comment by lucaswoj** [comment] 2016-12-22 14:42
Duplicate of #433

**Closed as completed by lucaswoj** 2016-12-22 14:42 UTC
Labels: documentation
