### ISSUE TITLE
Improve documentation for "light" property 

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-style-spec#538] opened 2016-10-14 00:01 UTC
Presently `light` has no documentation in the style spec.

This'll be tricky... Either we restructure "light" or we restructure our docs generator. 

<img width="787" alt="screen shot 2016-10-13 at 5 01 01 pm" src="https://cloud.githubusercontent.com/assets/281306/19371277/a7572e84-9166-11e6-939f-d57bd75beadd.png">

**Comment by jfirebaugh** [comment] 2016-10-14 19:04
Duplicate of #522.

**Closed as completed by jfirebaugh** 2016-10-14 19:04 UTC
