### ISSUE TITLE
Rename icon-rotate, text-rotate to icon-rotation, text-rotation

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-style-spec#648] opened 2017-01-05 11:10 UTC
The `icon-rotate` and `text-rotate` properties should be renamed `icon-rotation` and `text-rotation`, respectively, for consistency with `icon-rotation-alignment` and `text-rotation-alignment`. (It would also happen to be consistent with the iOS and macOS SDKs, which renamed these properties as part of mapbox/mapbox-gl-native#6098.)

/cc @lucaswoj @jfirebaugh

**Comment by 1ec5** [comment] 2017-01-05 11:18
Also, `raster-hue-rotate` would become `raster-hue-rotation`.

**Comment by jfirebaugh** [comment] 2017-01-05 17:04
Duplicate of #201.

**Closed as completed by jfirebaugh** 2017-01-05 17:04 UTC
Labels: breaking change
