### ISSUE TITLE
Add hover height to raster layers

### ISSUE THREAD

**Issue by IvanSanchez** [mapbox/mapbox-gl-style-spec#552] opened 2016-10-26 14:25 UTC
Feature request: Add a `raster-extrude-height` property to `raster` layers. Or `raster-hover-height`. Or something.

The use case is raster layers with alpha channel opacity which should "hover" above ground at a preset height, matching the top plane of extruded geometries. e.g. cropped aerial imagery for a given building rooftop.

**Comment by lucaswoj** [comment] 2017-02-01 23:26
Duplicate of #488

**Closed as completed by lucaswoj** 2017-02-01 23:26 UTC
